Explain Hückel, including molecular orbitals. Only based on simple rule, namely one (diagonal) energy term for the atom and one interaction term with closest neighbor.

# Benzene
## Energy

We will first use some arbitrary alpha and beta parameters, then try to find reasonable ones by comparing to the experiment/QM.

In [7]:
import numpy as np
alpha = 1
beta = 0.1
Benzene_H = np.array([[alpha, beta, 0, 0, 0, beta], [beta, alpha, beta, 0, 0, 0], [0, beta, alpha, beta, 0, 0], [0, 0, beta, alpha, beta, 0], [0, 0, 0, beta, alpha, beta], [beta, 0, 0, 0, beta, alpha]])
print(Benzene_H)

[[1.  0.1 0.  0.  0.  0.1]
 [0.1 1.  0.1 0.  0.  0. ]
 [0.  0.1 1.  0.1 0.  0. ]
 [0.  0.  0.1 1.  0.1 0. ]
 [0.  0.  0.  0.1 1.  0.1]
 [0.1 0.  0.  0.  0.1 1. ]]


In [8]:
eigenval, eigenvec = np.linalg.eigh(Benzene_H)
print(eigenval)

[0.8 0.9 0.9 1.1 1.1 1.2]


Change the values of alpha and beta:

In [9]:
alpha = 2
beta = 0.1
Benzene_H = np.array([[alpha, beta, 0, 0, 0, beta], [beta, alpha, beta, 0, 0, 0], [0, beta, alpha, beta, 0, 0], [0, 0, beta, alpha, beta, 0], [0, 0, 0, beta, alpha, beta], [beta, 0, 0, 0, beta, alpha]])
eigenval, eigenvec = np.linalg.eigh(Benzene_H)
print(eigenval)

[1.8 1.9 1.9 2.1 2.1 2.2]


In [10]:
alpha = 1
beta = 0.2
Benzene_H = np.array([[alpha, beta, 0, 0, 0, beta], [beta, alpha, beta, 0, 0, 0], [0, beta, alpha, beta, 0, 0], [0, 0, beta, alpha, beta, 0], [0, 0, 0, beta, alpha, beta], [beta, 0, 0, 0, beta, alpha]])
eigenval, eigenvec = np.linalg.eigh(Benzene_H)
print(eigenval)

[0.6 0.8 0.8 1.2 1.2 1.4]


Clearly, the energies are
* alpha - 2*beta
* alpha - beta (x2)
* alpha + beta (x2)
* alpha + 2*beta

This is indeed the correct structure. Now let's find beta by looking at (experimental) absorption energy. The first (weak) band is at 4.9 eV, followed by a less weak band at 6.19 and then an intense at 6.96 eV. We predict 2*beta, 3*beta. (Can we somehow do a small fit?).

From this we find that a good beta would be around 2.4 eV (alpha is only an energy shift, let's put it at 0).

In [11]:
alpha = 0
beta = 2.5
Benzene_H = np.array([[alpha, beta, 0, 0, 0, beta], [beta, alpha, beta, 0, 0, 0], [0, beta, alpha, beta, 0, 0], [0, 0, beta, alpha, beta, 0], [0, 0, 0, beta, alpha, beta], [beta, 0, 0, 0, beta, alpha]])
eigenval, eigenvec = np.linalg.eigh(Benzene_H)
print(eigenval)

[-5.  -2.5 -2.5  2.5  2.5  5. ]


Compute all excitation energies (and their multiplicities) and sort them:

In [13]:
exc_energies = []
for eig1 in eigenval[:3]:
    for eig2 in eigenval[3:]:
        exc_energies.append(eig2-eig1)
print(sorted(exc_energies))

[4.999999999999999, 4.999999999999999, 4.999999999999999, 4.999999999999999, 7.5, 7.5, 7.500000000000001, 7.500000000000001, 10.000000000000002]


## Plotting the orbitals

Plot the orbitals in 2D using the eigenvectors of the previous calculation and assuming a gaussian orbital shape. You can create a 2D grid of points and simply compute the value of the gaussians at each point, then multiply by the MO coefficients. Plot as a heat map. (Find some reasonable geometry and gaussian radius)

# Linear alkenes

Create a code that computes the energies of linear alkenes of increasing sizes. Use the previously found alpha and beta parameters and compute the excitation energy, plot it for increasing alkene sizes.

 If we want to go further, we can compare the result to a simple "particle in a box" model.